# Generated by Django 2.1.3 on 2019-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='imgurl',
            field=models.CharField(blank=True, default='gl', max_length=1000, null=True, verbose_name='头像路径'),
        ),
    ]
