# Generated by Django 2.1.3 on 2019-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191126_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_stu',
            name='institution',
            field=models.CharField(blank=True, default='工学院', max_length=128, null=True, verbose_name='学院'),
        ),
    ]
