# Generated by Django 2.1.3 on 2019-12-01 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='imageprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(blank=True, default='gl', max_length=1000, null=True, verbose_name='头像路径')),
            ],
            options={
                'verbose_name': '头像',
                'verbose_name_plural': '头像',
            },
        ),
        migrations.CreateModel(
            name='user_profile_stu',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile_stu', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identity', models.CharField(choices=[('1', '学生'), ('2', '老师')], default='1', max_length=128, verbose_name='用户身份')),
                ('phonenumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话号码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=128, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=128, null=True, verbose_name='年龄')),
                ('major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮件')),
                ('birth_data', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('institution', models.CharField(blank=True, default='工学院', max_length=128, null=True, verbose_name='学院')),
            ],
            options={
                'verbose_name': '学生个人信息',
                'verbose_name_plural': '学生个人信息',
            },
        ),
        migrations.CreateModel(
            name='user_profile_teh',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile_teh', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identity', models.CharField(choices=[('1', '学生'), ('2', '老师')], default='1', max_length=128, verbose_name='用户身份')),
                ('phonenumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话号码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=128, null=True, verbose_name='性别')),
                ('major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮件')),
                ('institution', models.CharField(blank=True, default='工学院', max_length=128, null=True, verbose_name='学院')),
            ],
            options={
                'verbose_name': '老师个人信息',
                'verbose_name_plural': '老师个人信息',
            },
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_imageprofile', to=settings.AUTH_USER_MODEL, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
