# Generated by Django 2.2.7 on 2019-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_stu',
            name='capability',
            field=models.FloatField(default=0.6, verbose_name='能力值'),
        ),
    ]
