# Generated by Django 2.2.7 on 2019-12-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_stu_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_stu',
            name='ans_history',
            field=models.TextField(default='{"0": -1, "1": -1}', verbose_name='做题历史'),
        ),
    ]
