# Generated by Django 2.2.7 on 2019-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_stu_ans_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_stu',
            name='identity',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='student', max_length=128, verbose_name='用户身份'),
        ),
        migrations.AlterField(
            model_name='user_profile_teh',
            name='identity',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='teacher', max_length=128, verbose_name='用户身份'),
        ),
    ]
