# Generated by Django 2.2.7 on 2019-11-21 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='课程名字')),
            ],
        ),
        migrations.CreateModel(
            name='Isvertify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu', models.CharField(default='', max_length=100, verbose_name='审核状态')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(verbose_name='题目ID')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('choice_a', models.TextField(default='A.', verbose_name='A选项')),
                ('choice_b', models.TextField(default='B.', verbose_name='B选项')),
                ('choice_c', models.TextField(default='C.', verbose_name='C选项')),
                ('choice_d', models.TextField(default='D.', verbose_name='D选项')),
                ('note', models.TextField(default='答案选XXX,因为XXX', verbose_name='备注信息')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('evaluate_score', models.IntegerField(verbose_name='题目得分')),
                ('true_rate', models.IntegerField(verbose_name='题目正确率')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.CourseList', verbose_name='所属课程')),
                ('statu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Isvertify', verbose_name='审核状态')),
            ],
        ),
    ]
