# Generated by Django 2.2.7 on 2019-11-27 03:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='课程名字')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='题目内容')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('choice_a', models.TextField(default='A.', verbose_name='A选项')),
                ('choice_b', models.TextField(default='B.', verbose_name='B选项')),
                ('choice_c', models.TextField(default='C.', verbose_name='C选项')),
                ('choice_d', models.TextField(default='D.', verbose_name='D选项')),
                ('note', models.TextField(default='答案选XXX,因为XXX', verbose_name='备注信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('count', models.IntegerField(default=0, verbose_name='提交人次')),
                ('evaluate_score', models.FloatField(default=0, verbose_name='题目得分')),
                ('true_rate', models.FloatField(default=0, verbose_name='题目正确率')),
                ('states', models.CharField(default='未通过', max_length=128, verbose_name='审核状态')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList', verbose_name='所属课程')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='Exersice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='生成时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属学生')),
            ],
            options={
                'ordering': ('-e_time',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.Question')),
                ('user_choice', models.CharField(default='', max_length=1, verbose_name='用户选择')),
                ('ie_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='做题时间')),
                ('exersice', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.Exersice', verbose_name='练习场次')),
            ],
            options={
                'ordering': ('-ie_time',),
            },
            bases=('course.question',),
        ),
    ]
