# Generated by Django 2.2.7 on 2019-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='states',
            field=models.CharField(default='待审核', max_length=128, verbose_name='审核状态'),
        ),
    ]
